<a href="https://colab.research.google.com/github/sevaradevoloper/machine-learning-class-work/blob/main/Takrorlash_imtihon_oldi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

# 1. Dataset yaratamiz
data = {
    'maydon': [50, 60, np.nan, 80, 50, 500],
    'narx': [400, 500, 550, 700, 400, 9500]
}
df = pd.DataFrame(data)
df

   maydon  narx
0    50.0   400
1    60.0   500
2     NaN   550
3    80.0   700
4    50.0   400
5   500.0  9500

In [5]:

# 2. Missing value'larni aniqlash va Median bilan to'ldirish
missing_count = df.isnull().sum()
med_maydon = df['maydon'].median()
df['maydon'] = df['maydon'].fillna(med_maydon)

# 3. Duplikatlarni o'chirish
df = df.drop_duplicates()

# 4. IQR yordamida outlier chegarasini hisoblash
Q1 = df['narx'].quantile(0.25)
Q3 = df['narx'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR
clean_df = df[df['narx'] <= upper_bound]

clean_df

   maydon  narx
0    50.0   400
1    60.0   500
2    60.0   550
3    80.0   700

In [19]:
df_work = pd.DataFrame({'tajriba': [1, 2, np.nan, 4, 2, 40]})
df_work
ortachasi = df_work["tajriba"].median()
df_work["tajriba"] = df_work["tajriba"].fillna(ortachasi)
df_work =df_work.drop_duplicates()
df_work

Q1 = df_work["tajriba"].quantile(0.25)
Q3 = df_work["tajriba"].quantile(0.75)
IQR = Q3-Q1
tepa = Q3+1.5*IQR


toza_df = df_work[df_work["tajriba"]<=tepa]
toza_df

   tajriba
0      1.0
1      2.0
3      4.0